# -*- coding: utf-8 -*-
# Notes: ==== Mind™ ====

import typing


CHAT_TEMPLATES: tuple[tuple[str, str], ...] = (
    ("你", "好"),
    ("你好", "，请介绍一下你自己"),
    ("你好呀", "，请介绍一下你自己"),
    ("hi", ", introduce yourself"),
    ("hello", ", introduce yourself"),
    ("hey", ", tell me what you can do"),
    ("yo", ", tell me what you can do"),
    ("嗨", "，请介绍一下你自己"),
    ("哈喽", "，请介绍一下你自己"),
    ("在吗", "，说说你能做什么"),
    ("你在吗", "，说说你能做什么"),
    ("you there", "? tell me what you can do"),
    ("who are you", "?"),
    ("what can you do", "?"),
    ("introduce yourself", ""),
    ("tell me what you can do", ""),
    ("who are you?", ""),
    ("what can you do?", ""),
    ("let's chat", " a bit"),
    ("chat", " a bit"),
    ("闲聊", "一下"),
    ("聊聊", "这个功能"),
    ("聊一下", "这个功能"),
    ("随便聊聊", "吧"),
    ("介绍一下你自己", ""),
    ("说说你能做什么", ""),
    ("请", "介绍一下你自己"),
    ("请你", "介绍一下你自己"),
    ("please", " introduce yourself"),
    ("can you", " introduce yourself"),
    ("介绍", "一下你自己"),
    ("你是", "谁"),
    ("你能", "做什么"),
    ("tell me", " about yourself"),
    ("tell me", " what you can do"),
    ("what are you", ""),
    ("帮我", "分析一下这个问题"),
    ("帮我看", "一下这个问题"),
    ("解释", "一下这个问题"),
    ("help me", " analyze this problem"),
    ("help me", " look into this problem"),
    ("explain", " this problem"),
    ("说说", "这个功能"),
    ("总结", "一下这个内容"),
    ("tell me about", " this feature"),
    ("summarize", " this content"),
    ("给我", "一个方案"),
    ("给我", "一个执行方案"),
    ("给我", "一个排查思路"),
    ("给个", "方案"),
    ("给个", "排查思路"),
    ("give me", " a plan"),
    ("give me", " an execution plan"),
    ("give me", " a troubleshooting approach"),
    ("怎么", "做"),
    ("怎么", "实现"),
    ("如何", "做"),
    ("如何", "实现"),
    ("怎样", "做"),
    ("怎样", "实现"),
    ("how to", " do this"),
    ("how to", " implement this"),
    ("how do I", " do this"),
    ("how do I", " implement this"),
    ("帮我排", "查一下这个问题"),
    ("帮我总", "结一下这个内容"),
    ("哪样", "更合适"),
    ("是否", "可以这样做"),
    ("能不能", "这样做"),
    ("可不可以", "这样做"),
    ("which is", " better"),
    ("why is", " this happening"),
    ("can I", " do it this way"),
    ("is there", " a better approach"),
    ("为什么", "会这样"),
    ("有没有", "更好的方案"),
)


BASE_CODING_AGENT_TEMPLATES: tuple[tuple[str, str], ...] = (
    ("code", " 审查并修改实现"),
    ("repo", " 扫描代码结构"),
    ("bug", " 定位根因并修复"),
    ("debug", " reproduce, inspect, patch, and verify"),
    ("fix", " the issue and run tests"),
    ("review", " current changes and identify risks"),
    ("trace", " 调用链路并定位问题"),
    ("inspect", " 相关实现并给出结论"),
    ("patch", " 最小改动并验证"),
    ("repro", " 复现问题并定位根因"),
    ("verify", " 运行验证并汇总结论"),
    ("test", " 运行相关测试"),
    ("tests", " 运行相关测试"),
    ("run", " relevant tests"),
    ("unit", " test 并修复失败"),
    ("lint", " 检查并修复代码风格"),
    ("type", " check 并修复类型问题"),
    ("typecheck", " 并修复类型问题"),
    ("build", " 构建并修复失败"),
    ("coverage", " 检查测试覆盖风险"),
    ("deps", " 检查依赖和版本问题"),
    ("dependency", " 检查依赖和版本问题"),
    ("refactor", " 小步重构并验证行为"),
    ("diff", " 检查当前改动"),
    ("git", " 查看当前改动"),
    ("rg", " 搜索相关代码"),
    ("shell", " 执行本地命令并分析结果"),
    ("cmd", " 执行本地命令并分析结果"),
    ("tool", " 调用工具并验证结果"),
    ("代码", "审查并修改实现"),
    ("仓库", "扫描代码结构"),
    ("审查", "当前改动并指出风险"),
    ("评审", "当前改动并指出风险"),
    ("排查", "失败原因并给出修复"),
    ("定位", "问题根因"),
    ("复现", "问题并定位根因"),
    ("修复", "问题并运行验证"),
    ("补丁", "最小改动并验证"),
    ("测试", "相关改动并汇总结果"),
    ("验证", "修改结果并汇总结论"),
    ("构建", "项目并修复失败"),
    ("类型", "检查并修复类型问题"),
    ("依赖", "检查依赖和版本问题"),
    ("覆盖率", "检查测试覆盖风险"),
    ("调用链", "跟踪并定位问题"),
    ("改动", "检查当前 diff"),
    ("差异", "检查当前 diff"),
)


MODE_ALIAS_TEMPLATES: dict[str, tuple[tuple[str, str], ...]] = {
    "chat": (
        ("adb", " 设备信息"),
        ("app", " 应用"),
        ("ui", " 元素"),
        ("tap", " 按钮"),
        ("input", " 输入文本"),
        ("text", " 输入文本"),
        ("swipe", " 滑动页面"),
        ("scroll", " 到目标元素"),
        ("screen", " 截图"),
        ("screenshot", " 截图"),
        ("record", " 录屏"),
        ("scrcpy", " 录屏"),
        ("monkey", " 测试"),
        ("framix", " 视频帧"),
        ("memrix", " 内存趋势"),
    ),
    "fast": (
        ("http", " 接口"),
        ("https", " 请求"),
        ("ws", " 连接"),
        ("websocket", " 消息"),
        ("sse", " 事件流"),
        ("gql", " 查询"),
        ("graphql", " 响应"),
        ("tcp", " 报文"),
        ("udp", " 报文"),
        ("smtp", " 邮件"),
        ("imap", " 邮件"),
        ("ftp", " 文件"),
        ("jwt", " 生成"),
        ("rsa", " 加密"),
        ("aes", " 加密"),
        ("ffmpeg", " 处理"),
    ),
    "plan": (
        ("scrcpy", " 录屏"),
        ("重复", "执行 3 次"),
        ("循环", "执行 3 次"),
    ),
    "xtra": (
        ("mcp", " 工具协作完成任务"),
        ("dbhub", " 查询数据库"),
        ("db", " 查询数据库"),
        ("database", " 查询数据库"),
        ("sql", " 查询"),
        ("browser", " 打开网页并提取证据"),
        ("web", " 打开网页并提取证据"),
        ("url", " 打开网页并提取证据"),
    ),
}


INTENT_GROUPS: tuple[tuple[str, int, tuple[tuple[str, str], ...]], ...] = (
    ("coding_agent", 96, (
        ("查看", "当前改动"),
        ("查看", "相关实现"),
        ("查看", "调用链路"),
        ("查看", "失败日志"),
        ("分析", "失败原因"),
        ("分析", "回归风险"),
        ("分析", "代码路径"),
        ("分析", "当前改动"),
        ("审查", "当前改动"),
        ("评审", "当前改动"),
        ("检查", "当前改动"),
        ("检查", "代码风格"),
        ("检查", "类型问题"),
        ("检查", "测试覆盖"),
        ("定位", "问题根因"),
        ("定位", "调用链路"),
        ("排查", "失败原因"),
        ("排查", "回归问题"),
        ("复现", "问题"),
        ("修复", "问题并跑测试"),
        ("修复", "测试失败"),
        ("修复", "类型错误"),
        ("修复", "展示问题"),
        ("修改", "代码并验证"),
        ("改", "代码并验证"),
        ("实现", "这个需求并验证"),
        ("补", "测试覆盖"),
        ("补充", "回归测试"),
        ("运行", "相关测试"),
        ("运行", "lint"),
        ("运行", "type check"),
        ("运行", "构建"),
        ("跑", "相关测试"),
        ("跑", "lint"),
        ("跑", "type check"),
        ("验证", "修改结果"),
        ("验证", "回归风险"),
        ("构建", "项目并修复失败"),
        ("重构", "相关实现并保持行为"),
        ("搜索", "相关代码"),
        ("梳理", "调用链路"),
        ("总结", "当前改动"),
        ("review", " current changes"),
        ("debug", " the failure"),
        ("inspect", " related implementation"),
        ("trace", " the call path"),
        ("fix", " the issue and run tests"),
        ("patch", " the minimal change and verify"),
        ("repro", " the issue"),
        ("run", " relevant tests"),
        ("verify", " the change"),
        ("refactor", " safely and verify behavior"),
        ("search", " related code"),
        ("summarize", " current changes"),
    )),
    ("device_connection", 88, (
        ("连", "设备"),
        ("连接", "设备"),
        ("连上", "设备"),
        ("连接到", "设备"),
        ("选择", "设备"),
        ("切换到", "设备"),
        ("查看", "设备信息"),
        ("获取", "设备信息"),
        ("抓取", "设备快照"),
    )),
    ("app_lifecycle", 86, (
        ("开", "应用"),
        ("开", "设置页应用"),
        ("打开", "应用"),
        ("进入", "应用"),
        ("启动", "应用"),
        ("停止", "应用"),
        ("关闭", "应用"),
        ("重启", "应用"),
        ("安装", "应用"),
        ("卸载", "应用"),
        ("清理", "应用数据"),
        ("拉起", "应用"),
        ("用 deeplink", "打开应用"),
        ("通过 deeplink", "打开应用"),
    )),
    ("ui_action", 92, (
        ("点", "按钮"),
        ("点击", "按钮"),
        ("双击", "按钮"),
        ("轻点", "按钮"),
        ("输", "入文本"),
        ("输入", "文本"),
        ("填写", "文本"),
        ("清空", "输入框"),
        ("发送", "文本"),
        ("滑动", "页面"),
        ("上滑", "页面"),
        ("下滑", "页面"),
        ("左滑", "页面"),
        ("右滑", "页面"),
        ("滚动", "到顶部"),
        ("滚动", "到底部"),
        ("滚动", "到目标元素"),
        ("滚", "动到目标元素"),
        ("查找", "元素"),
        ("定位", "元素"),
        ("修复", "元素定位"),
        ("等待", "元素出现"),
        ("等待", "元素消失"),
        ("查看", "当前焦点"),
        ("查看", "当前控件树"),
    )),
    ("keyevent", 76, (
        ("返回", "首页"),
        ("回到", "首页"),
        ("返回", "上一页"),
        ("打开", "最近任务"),
        ("打开", "菜单"),
        ("按下", "回车"),
        ("按下", "Tab"),
        ("按下", "删除键"),
        ("按下", "空格"),
        ("按下", "Escape"),
        ("调高", "音量"),
        ("调低", "音量"),
        ("静音", "媒体音量"),
        ("暂停", "媒体播放"),
        ("切到", "下一首"),
        ("切到", "上一首"),
    )),
    ("system", 82, (
        ("开", "设置"),
        ("开", "通知栏"),
        ("打开", "通知栏"),
        ("打开", "设置"),
        ("打开", "Wi-Fi"),
        ("打开", "蓝牙"),
        ("重置", "输入法"),
        ("重启", "设备"),
        ("解锁", "屏幕"),
        ("亮起", "屏幕"),
        ("熄灭", "屏幕"),
        ("打开", "蓝牙"),
        ("关闭", "蓝牙"),
        ("打开", "Wi-Fi"),
        ("关闭", "Wi-Fi"),
        ("打开", "数据网络"),
        ("关闭", "数据网络"),
        ("组合键", "操作"),
    )),
    ("file", 78, (
        ("拉取", "文件"),
        ("推送", "文件"),
        ("删除", "文件"),
        ("导出", "logcat"),
        ("清理", "logcat"),
    )),
    ("screen_capture", 84, (
        ("截", "图"),
        ("截图", ""),
        ("截取", "截图"),
        ("保存", "截图"),
        ("抓取", "截图"),
        ("录", "屏"),
        ("录屏", ""),
        ("开始", "录屏"),
        ("停止", "录屏"),
        ("保存", "录屏"),
        ("投屏", ""),
        ("开始", "投屏"),
        ("关闭", "投屏"),
    )),
    ("package_info", 70, (
        ("查看", "已安装应用"),
        ("查看", "系统包"),
        ("查询", "包名"),
        ("筛选", "安装包"),
    )),
    ("inspect_runtime", 64, (
        ("查看", "空闲状态"),
        ("查询", "空闲状态"),
        ("等待", "3 秒"),
        ("循环执行", "步骤"),
        ("按步骤", "执行任务"),
    )),
    ("security", 68, (
        ("计算", "sha256 摘要"),
        ("生成", "JWT"),
        ("验签", "JWT"),
        ("解析", "JWT"),
        ("生成", "RSA 签名"),
        ("验证", "RSA 签名"),
        ("加密", "RSA 密文"),
        ("解密", "RSA 密文"),
        ("做", "AES 加密"),
        ("做", "HMAC 签名"),
    )),
    ("network_http", 88, (
        ("发", "起 HTTP 请求"),
        ("看", "接口响应"),
        ("看", "接口结果"),
        ("看", "响应"),
        ("看", "请求结果"),
        ("请求", "HTTP 接口"),
        ("调用", "HTTP 接口"),
        ("发起", "HTTP 请求"),
        ("看", "HTTP 响应"),
        ("查看", "HTTP 响应"),
        ("分析", "HTTP 响应"),
        ("验证", "HTTP 接口"),
        ("批量", "请求 HTTP 接口"),
        ("预渲染", "HTTP 请求"),
        ("校验", "HTTP 请求"),
    )),
    ("network_sse_ws", 86, (
        ("连", "接 WebSocket"),
        ("看", "WebSocket 消息"),
        ("订阅", "SSE 事件流"),
        ("查看", "SSE 事件流"),
        ("采样", "SSE 事件流"),
        ("连接", "WebSocket"),
        ("查看", "WebSocket 消息"),
        ("验证", "WebSocket 回包"),
        ("批量", "订阅 SSE"),
        ("批量", "连接 WebSocket"),
    )),
    ("network_graphql", 84, (
        ("查", "询 GraphQL"),
        ("看", "GraphQL 响应"),
        ("请求", "GraphQL 接口"),
        ("查询", "GraphQL"),
        ("变更", "GraphQL"),
        ("批量", "执行 GraphQL"),
        ("校验", "GraphQL 响应"),
    )),
    ("network_socket", 80, (
        ("发", "送 TCP 报文"),
        ("发送", "TCP 报文"),
        ("验证", "TCP 回包"),
        ("批量", "发送 TCP 报文"),
        ("发送", "UDP 报文"),
        ("验证", "UDP 回包"),
        ("批量", "发送 UDP 报文"),
    )),
    ("network_mail_file", 78, (
        ("发送", "SMTP 邮件"),
        ("批量", "发送 SMTP 邮件"),
        ("读取", "IMAP 邮件"),
        ("批量", "读取 IMAP 邮件"),
        ("上传", "FTP 文件"),
        ("下载", "FTP 文件"),
        ("批量", "传输 FTP 文件"),
    )),
    ("performance_memrix", 90, (
        ("看", "内存趋势"),
        ("查看", "内存趋势"),
        ("分析", "内存趋势"),
        ("测试", "内存基线"),
        ("采样", "内存"),
        ("查看", "流畅度趋势"),
        ("分析", "流畅度趋势"),
        ("测试", "流畅度"),
        ("采样", "流畅度"),
        ("生成", "内存报告"),
        ("生成", "流畅度报告"),
    )),
    ("performance_framix", 89, (
        ("看", "首字上屏"),
        ("分析", "视频帧"),
        ("分析", "阶段帧"),
        ("生成", "阶段帧分析报告"),
        ("查看", "首字上屏"),
        ("查看", "尾字上屏"),
        ("查看", "流式 tokens"),
        ("测试", "端到端耗时"),
        ("分析", "页面切换速度"),
        ("分析", "启动速度"),
    )),
    ("stability_monkey", 85, (
        ("执行", "Monkey 测试"),
        ("注入", "随机事件"),
        ("跑", "稳定性扰动"),
        ("做", "Monkey 压测"),
    )),
    ("media_video", 90, (
        ("抽", "关键帧"),
        ("抽", "场景帧"),
        ("抽", "截图"),
        ("提取", "关键帧"),
        ("提取", "场景帧"),
        ("抽取", "截图"),
        ("探", "测视频信息"),
        ("导出", "图片序列"),
        ("裁剪", "视频"),
        ("缩放", "视频"),
        ("转码", "视频"),
        ("拼接", "视频"),
        ("换容器", "视频"),
        ("去掉", "音轨"),
        ("探测", "视频信息"),
    )),
    ("media_audio", 88, (
        ("提取", "音轨"),
        ("抽取", "音轨"),
        ("抽", "音轨"),
        ("播", "放音频"),
        ("听", "音频"),
        ("替换", "音轨"),
        ("转换", "音频格式"),
        ("播放", "音频"),
        ("试听", "音频"),
        ("导出", "mp3"),
        ("导出", "wav"),
    )),
    ("report", 72, (
        ("生成", "报告"),
        ("输出", "报告"),
        ("导出", "报告"),
        ("生成", "结果摘要"),
        ("输出", "执行结果"),
    )),
)


VERB_DOMAIN_WEIGHTS: dict[str, dict[str, int]] = {
    "打开": {"system": 100, "app_lifecycle": 98, "screen_capture": 92},
    "开": {"system": 98, "app_lifecycle": 96},
    "进入": {"app_lifecycle": 98, "system": 92},
    "启动": {"app_lifecycle": 98, "screen_capture": 90},
    "停止": {"app_lifecycle": 98, "screen_capture": 92},
    "关闭": {"app_lifecycle": 96, "screen_capture": 88, "system": 86},
    "重启": {"system": 100, "app_lifecycle": 94},
    "拉起": {"app_lifecycle": 100},
    "安装": {"app_lifecycle": 100},
    "卸载": {"app_lifecycle": 100},
    "清理": {"file": 96, "system": 92, "app_lifecycle": 88},
    "连接": {"device_connection": 100, "network_sse_ws": 90},
    "连": {"device_connection": 100, "network_sse_ws": 88},
    "连上": {"device_connection": 100},
    "连接到": {"device_connection": 100},
    "选择": {"device_connection": 100},
    "切换到": {"device_connection": 100},
    "查看": {"performance_memrix": 100, "performance_framix": 98, "ui_action": 96, "network_http": 94, "package_info": 92, "inspect_runtime": 88},
    "检查": {"coding_agent": 100},
    "看": {"network_http": 100, "network_sse_ws": 96, "network_graphql": 94, "performance_memrix": 90, "performance_framix": 88},
    "获取": {"device_connection": 98, "network_http": 96, "package_info": 92},
    "查": {"network_graphql": 96, "ui_action": 90, "package_info": 88},
    "查询": {"package_info": 96, "inspect_runtime": 92},
    "分析": {"coding_agent": 100, "performance_framix": 100, "performance_memrix": 100, "network_http": 94},
    "审查": {"coding_agent": 100},
    "评审": {"coding_agent": 100},
    "定位": {"coding_agent": 100, "ui_action": 100},
    "排查": {"coding_agent": 100},
    "复现": {"coding_agent": 100},
    "修复": {"coding_agent": 100, "ui_action": 96},
    "修改": {"coding_agent": 100},
    "改": {"coding_agent": 100},
    "实现": {"coding_agent": 100},
    "补": {"coding_agent": 100},
    "补充": {"coding_agent": 100},
    "运行": {"coding_agent": 100},
    "测试": {"performance_memrix": 100, "performance_framix": 96},
    "验证": {"coding_agent": 100, "network_http": 96, "network_sse_ws": 96, "network_socket": 94, "security": 92},
    "采样": {"performance_memrix": 100, "network_sse_ws": 86},
    "生成": {"report": 100, "performance_memrix": 96, "performance_framix": 96, "security": 88},
    "输出": {"report": 100},
    "导出": {"file": 98, "screen_capture": 96, "media_audio": 90, "report": 88},
    "请求": {"network_http": 100, "network_graphql": 96},
    "调用": {"network_http": 100},
    "发起": {"network_http": 100},
    "发": {"network_http": 96, "network_socket": 94},
    "订阅": {"network_sse_ws": 100},
    "校验": {"network_http": 96, "network_graphql": 94},
    "预渲染": {"network_http": 100},
    "批量": {"network_http": 96, "network_sse_ws": 96, "network_graphql": 96, "network_socket": 94, "network_mail_file": 94},
    "发送": {"network_socket": 100, "network_mail_file": 98, "ui_action": 86},
    "读取": {"network_mail_file": 100},
    "上传": {"network_mail_file": 100},
    "下载": {"network_mail_file": 100},
    "爬": {"network_http": 92},
    "抓取": {"screen_capture": 96, "device_connection": 86},
    "截图": {"screen_capture": 100},
    "截": {"screen_capture": 100},
    "截取": {"screen_capture": 100},
    "录": {"screen_capture": 100},
    "录屏": {"screen_capture": 100},
    "投屏": {"screen_capture": 100},
    "点击": {"ui_action": 100},
    "点": {"ui_action": 98},
    "双击": {"ui_action": 100},
    "轻点": {"ui_action": 100},
    "输": {"ui_action": 96},
    "输入": {"ui_action": 100},
    "填写": {"ui_action": 100},
    "清空": {"ui_action": 100},
    "滑动": {"ui_action": 100},
    "上滑": {"ui_action": 100},
    "下滑": {"ui_action": 100},
    "左滑": {"ui_action": 100},
    "右滑": {"ui_action": 100},
    "滚动": {"ui_action": 100},
    "滚": {"ui_action": 96},
    "查找": {"ui_action": 100},
    "等待": {"ui_action": 94, "inspect_runtime": 90},
    "返回": {"keyevent": 100},
    "回到": {"keyevent": 100},
    "按下": {"keyevent": 100},
    "调高": {"keyevent": 100},
    "调低": {"keyevent": 100},
    "静音": {"keyevent": 100},
    "暂停": {"keyevent": 100},
    "解锁": {"system": 100},
    "亮起": {"system": 100},
    "熄灭": {"system": 100},
    "组合键": {"system": 100},
    "执行": {"stability_monkey": 100},
    "重复": {"inspect_runtime": 98},
    "循环": {"inspect_runtime": 96},
    "注入": {"stability_monkey": 100},
    "跑": {"coding_agent": 100, "stability_monkey": 94, "inspect_runtime": 90},
    "构建": {"coding_agent": 100},
    "重构": {"coding_agent": 100},
    "搜索": {"coding_agent": 100},
    "梳理": {"coding_agent": 100},
    "review": {"coding_agent": 100},
    "debug": {"coding_agent": 100},
    "inspect": {"coding_agent": 100},
    "trace": {"coding_agent": 100},
    "fix": {"coding_agent": 100},
    "patch": {"coding_agent": 100},
    "repro": {"coding_agent": 100},
    "run": {"coding_agent": 100},
    "verify": {"coding_agent": 100},
    "refactor": {"coding_agent": 100},
    "search": {"coding_agent": 100},
    "summarize": {"coding_agent": 100},
    "做": {"security": 84, "stability_monkey": 82},
    "计算": {"security": 100},
    "验签": {"security": 100},
    "解析": {"security": 96},
    "加密": {"security": 100},
    "解密": {"security": 100},
    "提取": {"media_video": 100, "media_audio": 98},
    "抽": {"media_video": 100, "media_audio": 98},
    "抽取": {"media_video": 100, "media_audio": 98},
    "裁剪": {"media_video": 100},
    "缩放": {"media_video": 100},
    "转码": {"media_video": 100},
    "拼接": {"media_video": 100},
    "换容器": {"media_video": 100},
    "去掉": {"media_video": 100},
    "探测": {"media_video": 100},
    "探": {"media_video": 96},
    "替换": {"media_audio": 100},
    "转换": {"media_audio": 100},
    "播": {"media_audio": 100},
    "听": {"media_audio": 100},
    "播放": {"media_audio": 100},
    "试听": {"media_audio": 100},
}


def build_intent_templates() -> tuple[dict[str, typing.Any], ...]:
    return tuple(
        {
            "domain"       : domain,
            "group_weight" : weight,
            "verb"         : verb,
            "suggestion"   : suggestion,
            "order"        : order
        }
        for domain, weight, pairs in INTENT_GROUPS
        for order, (verb, suggestion) in enumerate(pairs)
    )


if __name__ == '__main__':
    pass
