import typing


COMMAND_TEMPLATES: dict[str, str] = {
    "/c": "hat",
    "/ch": "at",
    "/f": "ast",
    "/fa": "st",
    "/p": "lan",
    "/pl": "an",
    "/he": "lp",
    "/h": "elp",
    "/mo": "del ",
    "/model": " <model-name>",
    "/model ": "<model-name>",
    "/ap": "ikey ",
    "/api": "key ",
    "/apikey": " <api-key>",
    "/apikey ": "<api-key>",
    "/su": "bscription",
    "/sub": "scription",
    "/li": "cense",
    "/lic": "ense",
    "ex": "it",
    "qui": "t",
}


CHAT_TEMPLATES: tuple[tuple[str, str], ...] = (
    ("你", "好"),
    ("你好", "，请介绍一下你自己"),
    ("请", "介绍一下你自己"),
    ("请你", "介绍一下你自己"),
    ("介绍", "一下你自己"),
    ("你是", "谁"),
    ("你能", "做什么"),
    ("帮我", "分析一下这个问题"),
    ("帮我看", "一下这个问题"),
    ("解释", "一下这个问题"),
    ("说说", "这个功能"),
    ("总结", "一下这个内容"),
    ("给我", "一个方案"),
    ("给我", "一个执行方案"),
    ("给我", "一个排查思路"),
    ("怎么", "做"),
    ("怎么", "实现"),
    ("如何", "做"),
    ("如何", "实现"),
    ("怎样", "做"),
    ("怎样", "实现"),
    ("哪样", "更合适"),
    ("为什么", "会这样"),
    ("是否", "可以这样做"),
    ("能不能", "这样做"),
    ("可不可以", "这样做"),
    ("有没有", "更好的方案"),
)


INTENT_GROUPS: tuple[tuple[str, int, tuple[tuple[str, str], ...]], ...] = (
    ("device_connection", 88, (
        ("连接", "设备"),
        ("连上", "设备"),
        ("连接到", "设备"),
        ("选择", "设备"),
        ("切换到", "设备"),
        ("查看", "设备信息"),
        ("获取", "设备信息"),
        ("抓取", "设备快照"),
    )),
    ("app_lifecycle", 86, (
        ("打开", "应用"),
        ("进入", "应用"),
        ("启动", "应用"),
        ("停止", "应用"),
        ("关闭", "应用"),
        ("重启", "应用"),
        ("安装", "应用"),
        ("卸载", "应用"),
        ("清理", "应用数据"),
        ("拉起", "应用"),
        ("用 deeplink", "打开应用"),
        ("通过 deeplink", "打开应用"),
    )),
    ("ui_action", 92, (
        ("点击", "按钮"),
        ("双击", "按钮"),
        ("轻点", "按钮"),
        ("输入", "文本"),
        ("填写", "文本"),
        ("清空", "输入框"),
        ("发送", "文本"),
        ("滑动", "页面"),
        ("上滑", "页面"),
        ("下滑", "页面"),
        ("左滑", "页面"),
        ("右滑", "页面"),
        ("滚动", "到顶部"),
        ("滚动", "到底部"),
        ("滚动", "到目标元素"),
        ("查找", "元素"),
        ("定位", "元素"),
        ("修复", "元素定位"),
        ("等待", "元素出现"),
        ("等待", "元素消失"),
        ("查看", "当前焦点"),
        ("查看", "当前控件树"),
    )),
    ("keyevent", 76, (
        ("返回", "首页"),
        ("回到", "首页"),
        ("返回", "上一页"),
        ("打开", "最近任务"),
        ("打开", "菜单"),
        ("按下", "回车"),
        ("按下", "Tab"),
        ("按下", "删除键"),
        ("按下", "空格"),
        ("按下", "Escape"),
        ("调高", "音量"),
        ("调低", "音量"),
        ("静音", "媒体音量"),
        ("暂停", "媒体播放"),
        ("切到", "下一首"),
        ("切到", "上一首"),
    )),
    ("system", 82, (
        ("打开", "通知栏"),
        ("打开", "设置"),
        ("重置", "输入法"),
        ("重启", "设备"),
        ("解锁", "屏幕"),
        ("亮起", "屏幕"),
        ("熄灭", "屏幕"),
        ("打开", "蓝牙"),
        ("关闭", "蓝牙"),
        ("打开", "Wi-Fi"),
        ("关闭", "Wi-Fi"),
        ("打开", "数据网络"),
        ("关闭", "数据网络"),
        ("组合键", "操作"),
    )),
    ("file", 78, (
        ("拉取", "文件"),
        ("推送", "文件"),
        ("删除", "文件"),
        ("导出", "logcat"),
        ("清理", "logcat"),
    )),
    ("screen_capture", 84, (
        ("截图", ""),
        ("截取", "截图"),
        ("保存", "截图"),
        ("抓取", "截图"),
        ("录", "屏"),
        ("录屏", ""),
        ("开始", "录屏"),
        ("停止", "录屏"),
        ("保存", "录屏"),
        ("投屏", ""),
        ("开始", "投屏"),
        ("关闭", "投屏"),
    )),
    ("package_info", 70, (
        ("查看", "已安装应用"),
        ("查看", "系统包"),
        ("查询", "包名"),
        ("筛选", "安装包"),
    )),
    ("inspect_runtime", 64, (
        ("查看", "空闲状态"),
        ("查询", "空闲状态"),
        ("等待", "3 秒"),
        ("循环执行", "步骤"),
        ("按步骤", "执行任务"),
        ("跑", "自由规则"),
    )),
    ("security", 68, (
        ("计算", "sha256 摘要"),
        ("生成", "JWT"),
        ("验签", "JWT"),
        ("解析", "JWT"),
        ("生成", "RSA 签名"),
        ("验证", "RSA 签名"),
        ("加密", "RSA 密文"),
        ("解密", "RSA 密文"),
        ("做", "AES 加密"),
        ("做", "HMAC 签名"),
    )),
    ("network_http", 88, (
        ("请求", "HTTP 接口"),
        ("调用", "HTTP 接口"),
        ("发起", "HTTP 请求"),
        ("查看", "HTTP 响应"),
        ("分析", "HTTP 响应"),
        ("验证", "HTTP 接口"),
        ("批量", "请求 HTTP 接口"),
        ("预渲染", "HTTP 请求"),
        ("校验", "HTTP 请求"),
    )),
    ("network_sse_ws", 86, (
        ("订阅", "SSE 事件流"),
        ("查看", "SSE 事件流"),
        ("采样", "SSE 事件流"),
        ("连接", "WebSocket"),
        ("查看", "WebSocket 消息"),
        ("验证", "WebSocket 回包"),
        ("批量", "订阅 SSE"),
        ("批量", "连接 WebSocket"),
    )),
    ("network_graphql", 84, (
        ("请求", "GraphQL 接口"),
        ("查询", "GraphQL"),
        ("变更", "GraphQL"),
        ("批量", "执行 GraphQL"),
        ("校验", "GraphQL 响应"),
    )),
    ("network_socket", 80, (
        ("发送", "TCP 报文"),
        ("验证", "TCP 回包"),
        ("批量", "发送 TCP 报文"),
        ("发送", "UDP 报文"),
        ("验证", "UDP 回包"),
        ("批量", "发送 UDP 报文"),
    )),
    ("network_mail_file", 78, (
        ("发送", "SMTP 邮件"),
        ("批量", "发送 SMTP 邮件"),
        ("读取", "IMAP 邮件"),
        ("批量", "读取 IMAP 邮件"),
        ("上传", "FTP 文件"),
        ("下载", "FTP 文件"),
        ("批量", "传输 FTP 文件"),
    )),
    ("performance_memrix", 90, (
        ("查看", "内存趋势"),
        ("分析", "内存趋势"),
        ("测试", "内存基线"),
        ("采样", "内存"),
        ("查看", "流畅度趋势"),
        ("分析", "流畅度趋势"),
        ("测试", "流畅度"),
        ("采样", "流畅度"),
        ("生成", "内存报告"),
        ("生成", "流畅度报告"),
    )),
    ("performance_framix", 89, (
        ("分析", "视频帧"),
        ("分析", "阶段帧"),
        ("生成", "阶段帧分析报告"),
        ("查看", "首字上屏"),
        ("查看", "尾字上屏"),
        ("查看", "流式 tokens"),
        ("测试", "端到端耗时"),
        ("分析", "页面切换速度"),
        ("分析", "启动速度"),
    )),
    ("stability_monkey", 85, (
        ("执行", "Monkey 测试"),
        ("注入", "随机事件"),
        ("跑", "稳定性扰动"),
        ("做", "Monkey 压测"),
    )),
    ("media_video", 90, (
        ("提取", "关键帧"),
        ("提取", "场景帧"),
        ("抽取", "截图"),
        ("导出", "图片序列"),
        ("裁剪", "视频"),
        ("缩放", "视频"),
        ("转码", "视频"),
        ("拼接", "视频"),
        ("换容器", "视频"),
        ("去掉", "音轨"),
        ("探测", "视频信息"),
    )),
    ("media_audio", 88, (
        ("提取", "音轨"),
        ("抽取", "音轨"),
        ("替换", "音轨"),
        ("转换", "音频格式"),
        ("播放", "音频"),
        ("试听", "音频"),
        ("导出", "mp3"),
        ("导出", "wav"),
    )),
    ("report", 72, (
        ("生成", "报告"),
        ("输出", "报告"),
        ("导出", "报告"),
        ("生成", "结果摘要"),
        ("输出", "执行结果"),
    )),
)


VERB_DOMAIN_WEIGHTS: dict[str, dict[str, int]] = {
    "打开": {"system": 100, "app_lifecycle": 98, "screen_capture": 92},
    "进入": {"app_lifecycle": 98, "system": 92},
    "启动": {"app_lifecycle": 98, "screen_capture": 90},
    "停止": {"app_lifecycle": 98, "screen_capture": 92},
    "关闭": {"app_lifecycle": 96, "screen_capture": 88, "system": 86},
    "重启": {"system": 100, "app_lifecycle": 94},
    "拉起": {"app_lifecycle": 100},
    "安装": {"app_lifecycle": 100},
    "卸载": {"app_lifecycle": 100},
    "清理": {"file": 96, "system": 92, "app_lifecycle": 88},
    "连接": {"device_connection": 100, "network_sse_ws": 90},
    "连上": {"device_connection": 100},
    "连接到": {"device_connection": 100},
    "选择": {"device_connection": 100},
    "切换到": {"device_connection": 100},
    "查看": {"performance_memrix": 100, "performance_framix": 98, "ui_action": 96, "network_http": 94, "package_info": 92, "inspect_runtime": 88},
    "获取": {"device_connection": 98, "network_http": 96, "package_info": 92},
    "查询": {"package_info": 96, "inspect_runtime": 92},
    "分析": {"performance_framix": 100, "performance_memrix": 100, "network_http": 94},
    "测试": {"performance_memrix": 100, "performance_framix": 96},
    "采样": {"performance_memrix": 100, "network_sse_ws": 86},
    "生成": {"report": 100, "performance_memrix": 96, "performance_framix": 96, "security": 88},
    "输出": {"report": 100},
    "导出": {"file": 98, "screen_capture": 96, "media_audio": 90, "report": 88},
    "请求": {"network_http": 100, "network_graphql": 96},
    "调用": {"network_http": 100},
    "发起": {"network_http": 100},
    "订阅": {"network_sse_ws": 100},
    "验证": {"network_http": 96, "network_sse_ws": 96, "network_socket": 94, "security": 92},
    "校验": {"network_http": 96, "network_graphql": 94},
    "预渲染": {"network_http": 100},
    "批量": {"network_http": 96, "network_sse_ws": 96, "network_graphql": 96, "network_socket": 94, "network_mail_file": 94},
    "发送": {"network_socket": 100, "network_mail_file": 98, "ui_action": 86},
    "读取": {"network_mail_file": 100},
    "上传": {"network_mail_file": 100},
    "下载": {"network_mail_file": 100},
    "爬": {"network_http": 92},
    "抓取": {"screen_capture": 96, "device_connection": 86},
    "截图": {"screen_capture": 100},
    "截取": {"screen_capture": 100},
    "录": {"screen_capture": 100},
    "录屏": {"screen_capture": 100},
    "投屏": {"screen_capture": 100},
    "点击": {"ui_action": 100},
    "双击": {"ui_action": 100},
    "轻点": {"ui_action": 100},
    "输入": {"ui_action": 100},
    "填写": {"ui_action": 100},
    "清空": {"ui_action": 100},
    "滑动": {"ui_action": 100},
    "上滑": {"ui_action": 100},
    "下滑": {"ui_action": 100},
    "左滑": {"ui_action": 100},
    "右滑": {"ui_action": 100},
    "滚动": {"ui_action": 100},
    "查找": {"ui_action": 100},
    "定位": {"ui_action": 100},
    "修复": {"ui_action": 96},
    "等待": {"ui_action": 94, "inspect_runtime": 90},
    "返回": {"keyevent": 100},
    "回到": {"keyevent": 100},
    "按下": {"keyevent": 100},
    "调高": {"keyevent": 100},
    "调低": {"keyevent": 100},
    "静音": {"keyevent": 100},
    "暂停": {"keyevent": 100},
    "解锁": {"system": 100},
    "亮起": {"system": 100},
    "熄灭": {"system": 100},
    "组合键": {"system": 100},
    "执行": {"stability_monkey": 100},
    "注入": {"stability_monkey": 100},
    "跑": {"stability_monkey": 94, "inspect_runtime": 90},
    "做": {"security": 84, "stability_monkey": 82},
    "计算": {"security": 100},
    "验签": {"security": 100},
    "解析": {"security": 96},
    "加密": {"security": 100},
    "解密": {"security": 100},
    "提取": {"media_video": 100, "media_audio": 98},
    "抽取": {"media_video": 100, "media_audio": 98},
    "裁剪": {"media_video": 100},
    "缩放": {"media_video": 100},
    "转码": {"media_video": 100},
    "拼接": {"media_video": 100},
    "换容器": {"media_video": 100},
    "去掉": {"media_video": 100},
    "探测": {"media_video": 100},
    "替换": {"media_audio": 100},
    "转换": {"media_audio": 100},
    "播放": {"media_audio": 100},
    "试听": {"media_audio": 100},
    "循环执行": {"inspect_runtime": 100},
}


def build_intent_templates() -> tuple[dict[str, typing.Any], ...]:
    return tuple(
        {
            "domain": domain,
            "group_weight": weight,
            "verb": verb,
            "suggestion": suggestion,
            "order": order,
        }
        for domain, weight, pairs in INTENT_GROUPS
        for order, (verb, suggestion) in enumerate(pairs)
    )
